version: '3.9'

services:
  web:
    container_name: my-awesome-app-drs-dev
    build:
      context: .
      dockerfile: Dockerfile
  test:
    container_name: my-awesome-app-drs-dev-test
    build:
      context: ./
      dockerfile: Dockerfile
    command: ['npm', 'run', 'test']
