name: Base Image Options
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Single-Command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello out there

  Multi-line:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
          echo
          java -version
          echo
          git --version
          echo
          mvn -v
          Gradle -v
          ant -version
          echo
          echo $ANDROID_SDK_ROOT
