name: Docker Test Image CI

env:
  DATE_STAMP: $(date +%s)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Env vars
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

      - name: Build Docker Img
        run: docker build . --file Dockerfile --tag dstoffels/my-awesome-app-drs:${{ env.date-stamp }}

      - name: Run Tests
        run: docker run dstoffels/my-awesome-app-drs:${{ env.date-stamp }} npm run test
