# AKIASASMH6BDMWXMCDFX
# 7qy8Nx/qRLJPgfRJ+pqDVwd0IHVvjBS9sD02tOn4

name: Production Build (docker)

env:
  DATE_STAMP: $(date +%s)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env vars
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

      - name: build docker image
        run: docker build . --file Dockerfile --tag dstoffels/my-awesome-app-drs:latest

      - name: Add "date-stamp" tag to image
        run: docker image tag dstoffels/my-awesome-app-drs:latest dstoffels/my-awesome-app-drs:${{env.date-stamp}}

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to docker hub
        run: docker push --all-tags dstoffels/my-awesome-app-drs
