name: Docker Dev Image CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  DATE_STAMP: ${date +%s}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Env vars
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB

      - name: Build Docker Img
        run: docker build . --file Dockerfile --tag dstoffels/my-awesome-app-drs:latest
